server:
  port: 8081

spring:
  application:
    name: auth-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/grambasket_auth_db
  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: "mysupersecurekeymysupersecurekeymysupersecurekeymysupersecurekey12"

auth:
  jwt:
    expiration: 3600000 # 1 hour
    refresh-expiration: 604800000 # 7 days
    issuer: grambasket-auth-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    root: INFO
    com.grambasket.authservice: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%15.15t] [%-40.40logger{39}] : %msg%n"
  file:
    name: logs/auth-service.log

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
