server:
  port: 8089

spring:
  application:
    name: payment-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/grambasket_payment_db

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true