server:
  port: 8092

spring:
  application:
    name: review-rating-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/grambasket_review_db

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
