server:
  port: 8085

spring:
  application:
    name: user-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/grambasket_user_db
  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: "mysupersecretkeymysupersecretkey12"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    root: INFO
    com.grambasket.userservice: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%15.15t] [%-40.40logger{39}] : %msg%n"
  file:
    name: logs/user-service.log

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always