server:
  port: 8084

spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/grambasket_product_db

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
