server:
  port: 8086

spring:
  application:
    name: inventory-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/grambasket_inventory_db

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true