server:
  port: 8091

spring:
  application:
    name: delivery-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/grambasket_delivery_db

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

